/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout All */
        post: operations["logout_all_api_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AccountStatus: "new" | "open" | "closed" | "other";
        /** @enum {string} */
        AccountType: "broker" | "iis" | "invest_box" | "invest_fund" | "other";
        /** @enum {string} */
        AnswerStyle: "concise" | "detailed";
        /** ArtifactCreatedEvent */
        ArtifactCreatedEvent: {
            /** Seq */
            seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "artifact.created";
            artifact: components["schemas"]["ArtifactOut"];
        };
        /** ArtifactOut */
        ArtifactOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Local Id */
            local_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "chart" | "table" | "image";
            /** Spec */
            spec: components["schemas"]["ChartSpec"] | components["schemas"]["TableSpec"] | components["schemas"]["ImageSpec"];
            /** Image Url */
            image_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AxisSpec */
        AxisSpec: {
            /**
             * Type
             * @enum {string}
             */
            type: "time" | "category" | "value" | "log";
            /** Label */
            label: string | null;
            /** Format */
            format: ("date" | "month" | "quarter" | "year" | "money" | "percent" | "number" | "compact") | null;
            /** Unit */
            unit: string | null;
        };
        /** BrokerAccountOut */
        BrokerAccountOut: {
            /** Alias */
            alias: string;
            /** Name */
            name: string;
            type: components["schemas"]["AccountType"];
            status: components["schemas"]["AccountStatus"];
            /** Opened At */
            opened_at: string | null;
            /** Is Hidden */
            is_hidden: boolean;
        };
        /** BrokerConnectionOut */
        BrokerConnectionOut: {
            /** Connected */
            connected: boolean;
            /** Status */
            status: ("active" | "invalid") | null;
            /** Token Hint */
            token_hint: string | null;
            /** Last Verified At */
            last_verified_at: string | null;
            /** Accounts */
            accounts: components["schemas"]["BrokerAccountOut"][];
        };
        /** @enum {string} */
        ChartKind: "line" | "area" | "bar" | "stacked_bar" | "pie" | "candlestick" | "scatter" | "heatmap" | "waterfall";
        /** ChartPoint */
        ChartPoint: {
            /** X */
            x: string | number;
            /** Y */
            y: number | null;
            /** O */
            o: number | null;
            /** H */
            h: number | null;
            /** L */
            l: number | null;
            /** C */
            c: number | null;
            /** Y Cat */
            y_cat: string | null;
            /** Z */
            z: number | null;
        };
        /**
         * ChartSpec
         * @description Floats serve display only; exact values live in a TableSpec as DecimalStr.
         */
        ChartSpec: {
            kind: components["schemas"]["ChartKind"];
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string | null;
            x: components["schemas"]["AxisSpec"];
            y: components["schemas"]["AxisSpec"];
            y2: components["schemas"]["AxisSpec"] | null;
            /** Series */
            series: components["schemas"]["SeriesSpec"][];
            /**
             * Source Ids
             * @default []
             */
            source_ids: string[];
        };
        /** ColumnSpec */
        ColumnSpec: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "number" | "money" | "percent" | "date" | "instrument";
            /** Currency */
            currency: string | null;
            /** Digits */
            digits: number | null;
        };
        DecimalStr: string;
        /**
         * DevEchoEvent
         * @description Only in dev and ci (POST /api/dev/echo).
         */
        DevEchoEvent: {
            /** Seq */
            seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "dev.echo";
            /** Payload */
            payload: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** @enum {string} */
        ErrorCode: "unauthorized" | "invalid_credentials" | "forbidden" | "registration_closed" | "not_found" | "conflict" | "run_active" | "email_taken" | "broker_not_connected" | "gone" | "validation_error" | "invite_required" | "invite_invalid" | "token_invalid" | "token_not_read_only" | "rate_limited" | "user_budget_exhausted" | "llm_busy" | "llm_quota_exhausted" | "tinvest_unavailable" | "tinvest_rate_limited" | "web_unavailable" | "web_credits_exhausted" | "disclosure_unavailable" | "internal";
        /** ErrorOut */
        ErrorOut: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Details */
            details: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Request Id */
            request_id: string;
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** ImageSpec */
        ImageSpec: {
            /**
             * Source
             * @enum {string}
             */
            source: "logo" | "web" | "document_page";
            /** Logo Base */
            logo_base: string | null;
            /** Url */
            url: string | null;
            /** Document Id */
            document_id: string | null;
            /** Page */
            page: number | null;
            /** Alt */
            alt: string;
            /** Caption */
            caption: string | null;
            /**
             * Size
             * @default md
             * @enum {string}
             */
            size: "sm" | "md" | "lg";
            /**
             * Source Ids
             * @default []
             */
            source_ids: string[];
        };
        /** InstrumentBrief */
        InstrumentBrief: {
            /**
             * Uid
             * Format: uuid
             */
            uid: string;
            /** Ticker */
            ticker: string;
            /** Class Code */
            class_code: string;
            /** Name */
            name: string;
            instrument_type: components["schemas"]["InstrumentType"];
            /** Currency */
            currency: string;
            /** Logo Url */
            logo_url: string | null;
            /** Brand Color */
            brand_color: string | null;
        };
        /** @enum {string} */
        InstrumentType: "share" | "bond" | "etf" | "currency" | "future" | "option" | "structured" | "index" | "other";
        /** @enum {string} */
        Intent: "smalltalk" | "help" | "portfolio_status" | "portfolio_analysis" | "instrument_quote" | "instrument_analysis" | "compare" | "financials" | "news" | "research" | "other";
        JsonValue: unknown;
        /** LlmGateOut */
        LlmGateOut: {
            /** Capacity */
            capacity: number;
            /** In Use */
            in_use: number;
            /** Waiting */
            waiting: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserOut"];
            settings: components["schemas"]["SettingsOut"];
            broker: components["schemas"]["BrokerConnectionOut"];
        };
        /** @enum {string} */
        ModelFamily: "lite" | "pro" | "max" | "ultra";
        /** @enum {string} */
        ModelMode: "auto" | "lite" | "pro" | "max" | "ultra";
        /** Money */
        Money: {
            amount: components["schemas"]["DecimalStr"];
            /** Currency */
            currency: string;
        };
        /** PasswordChangeIn */
        PasswordChangeIn: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** @enum {string} */
        PeriodCode: "1m" | "3m" | "6m" | "ytd" | "1y" | "3y" | "5y" | "max";
        /** ReadyOut */
        ReadyOut: {
            /** Db */
            db: boolean;
            /** Qdrant */
            qdrant: boolean;
            /** Queue */
            queue: boolean;
            llm_gate: components["schemas"]["LlmGateOut"];
        };
        /** RegisterIn */
        RegisterIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Invite Code */
            invite_code?: string | null;
            /** Display Name */
            display_name?: string | null;
        };
        /**
         * RunFinishedEvent
         * @description Always the last event; the client then takes the answer from REST.
         */
        RunFinishedEvent: {
            /** Seq */
            seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.finished";
            status: components["schemas"]["RunStatus"];
            /** Message Id */
            message_id: string | null;
            error: components["schemas"]["ErrorOut"] | null;
        };
        /** RunQueuedEvent */
        RunQueuedEvent: {
            /** Seq */
            seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.queued";
            /** Position */
            position: number;
        };
        /** RunRoutedEvent */
        RunRoutedEvent: {
            /** Seq */
            seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.routed";
            intent: components["schemas"]["Intent"];
            family: components["schemas"]["ModelFamily"];
            /** Model Id */
            model_id: string;
            /** Reason */
            reason: string;
        };
        /** RunStartedEvent */
        RunStartedEvent: {
            /** Seq */
            seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.started";
        };
        /** @enum {string} */
        RunStatus: "queued" | "running" | "done" | "partial" | "cancelled" | "failed" | "interrupted";
        /** RunWarningEvent */
        RunWarningEvent: {
            /** Seq */
            seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.warning";
            code: components["schemas"]["WarningCode"];
            /** Message */
            message: string;
        };
        /** SeriesSpec */
        SeriesSpec: {
            /** Name */
            name: string;
            /** Points */
            points: components["schemas"]["ChartPoint"][];
            /**
             * Axis
             * @default y
             * @enum {string}
             */
            axis: "y" | "y2";
            /** Role */
            role: ("primary" | "positive" | "negative" | "neutral" | "benchmark") | null;
        };
        /** SettingsOut */
        SettingsOut: {
            model_mode: components["schemas"]["ModelMode"];
            answer_style: components["schemas"]["AnswerStyle"];
            /** Default Account */
            default_account: string | null;
        };
        /** SourceAddedEvent */
        SourceAddedEvent: {
            /** Seq */
            seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "source.added";
            source: components["schemas"]["SourceRef"];
        };
        /** SourceRef */
        SourceRef: {
            /** Local Id */
            local_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "web" | "document" | "tinvest" | "edisclosure";
            /** Title */
            title: string;
            /** Url */
            url: string | null;
            /** Publisher */
            publisher: string | null;
            /** Published At */
            published_at: string | null;
            /** Document Id */
            document_id: string | null;
            /** Page */
            page: number | null;
            /** Snippet */
            snippet: string | null;
        };
        /** StepStartedEvent */
        StepStartedEvent: {
            /** Seq */
            seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step.started";
            /** Step */
            step: number;
        };
        StreamEvent: components["schemas"]["RunQueuedEvent"] | components["schemas"]["RunStartedEvent"] | components["schemas"]["RunRoutedEvent"] | components["schemas"]["StepStartedEvent"] | components["schemas"]["ToolStartedEvent"] | components["schemas"]["ToolFinishedEvent"] | components["schemas"]["ArtifactCreatedEvent"] | components["schemas"]["SourceAddedEvent"] | components["schemas"]["TextDeltaEvent"] | components["schemas"]["TextResetEvent"] | components["schemas"]["RunWarningEvent"] | components["schemas"]["RunFinishedEvent"] | components["schemas"]["DevEchoEvent"];
        /** TableSpec */
        TableSpec: {
            /** Title */
            title: string;
            /** Columns */
            columns: components["schemas"]["ColumnSpec"][];
            /** Rows */
            rows: {
                [key: string]: string | null;
            }[];
            /** Total */
            total: {
                [key: string]: string | null;
            } | null;
            /** Note */
            note: string | null;
            /**
             * Instruments
             * @default {}
             */
            instruments: {
                [key: string]: components["schemas"]["InstrumentBrief"];
            };
            /**
             * Source Ids
             * @default []
             */
            source_ids: string[];
        };
        /** TextDeltaEvent */
        TextDeltaEvent: {
            /** Seq */
            seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text.delta";
            /** Delta */
            delta: string;
        };
        /**
         * TextResetEvent
         * @description The model called a function after some text: the client drops the text so far.
         */
        TextResetEvent: {
            /** Seq */
            seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text.reset";
        };
        /** ToolFinishedEvent */
        ToolFinishedEvent: {
            /** Seq */
            seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.finished";
            /** Step */
            step: number;
            /** Call Id */
            call_id: string;
            tool: components["schemas"]["ToolName"];
            /** Ok */
            ok: boolean;
            /** Summary */
            summary: string;
            error_code: components["schemas"]["ErrorCode"] | null;
            /** Duration Ms */
            duration_ms: number;
        };
        /** @enum {string} */
        ToolName: "portfolio_overview" | "portfolio_positions" | "operations_summary" | "portfolio_risk" | "instrument_lookup" | "instrument_profile" | "price_history" | "compare_instruments" | "issuer_reports" | "financials" | "docs_search" | "web_search" | "web_extract" | "web_crawl" | "make_chart" | "make_table" | "calc";
        /** ToolStartedEvent */
        ToolStartedEvent: {
            /** Seq */
            seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.started";
            /** Step */
            step: number;
            /** Call Id */
            call_id: string;
            tool: components["schemas"]["ToolName"];
            /** Title */
            title: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "owner";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** @enum {string} */
        WarningCode: "model_downgraded" | "budget_low" | "web_credits_low" | "tool_failed" | "steps_limit" | "ungrounded_numbers" | "partial_answer" | "unknown_placeholder" | "broker_not_connected";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    logout_all_api_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    change_password_api_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
