"""Embeddings port (tech.md §8.6): computed locally, the LLM stream stays free."""

from typing import Protocol

from app.contracts.vectors import SparseVec


class EmbeddingsPort(Protocol):
    def dense_dim(self) -> int: ...
    async def embed_passages(self, texts: list[str]) -> list[list[float]]: ...
    async def embed_query(self, text: str) -> list[float]: ...
    async def sparse_passages(self, texts: list[str]) -> list[SparseVec]: ...
    async def sparse_query(self, text: str) -> SparseVec: ...
