"""schema

Revision ID: 3d311d27300c
Revises:
Create Date: 2026-09-29 10:03:22.589687
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3d311d27300c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The trigram indexes need pg_trgm (§5.1).
    op.execute("create extension if not exists pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("figi", sa.Text(), nullable=True),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("class_code", sa.Text(), nullable=False),
        sa.Column("isin", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("instrument_type", sa.Text(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("lot", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("asset_uid", sa.Uuid(), nullable=True),
        sa.Column("brand_uid", sa.Uuid(), nullable=True),
        sa.Column("logo_base", sa.Text(), nullable=True),
        sa.Column("brand_color", sa.Text(), nullable=True),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("country_iso", sa.Text(), nullable=True),
        sa.Column("exchange", sa.Text(), nullable=True),
        sa.Column("for_qual_only", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "instrument_type in ('share','bond','etf','currency','future','option','structured','index','other')",
            name=op.f("instruments_instrument_type_check"),
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("instruments_pkey")),
        sa.UniqueConstraint("ticker", "class_code", name=op.f("instruments_ticker_class_code_key")),
    )
    op.create_index("instruments_asset_idx", "instruments", ["asset_uid"], unique=False)
    op.create_index("instruments_figi_idx", "instruments", ["figi"], unique=False)
    op.create_index("instruments_isin_idx", "instruments", ["isin"], unique=False)
    op.create_index(
        "instruments_name_trgm",
        "instruments",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "instruments_ticker_trgm",
        "instruments",
        ["ticker"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"ticker": "gin_trgm_ops"},
    )
    op.create_table(
        "issuers",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("inn", sa.Text(), nullable=True),
        sa.Column("ogrn", sa.Text(), nullable=True),
        sa.Column("edisclosure_id", sa.Integer(), nullable=True),
        sa.Column("asset_uid", sa.Uuid(), nullable=True),
        sa.Column("brand_uid", sa.Uuid(), nullable=True),
        sa.Column("resolve_status", sa.Text(), server_default="unresolved", nullable=False),
        sa.Column("resolve_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "resolve_status in ('manual','auto_confirmed','auto_candidate','unresolved')",
            name=op.f("issuers_resolve_status_check"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("issuers_pkey")),
        sa.UniqueConstraint("asset_uid", name=op.f("issuers_asset_uid_key")),
        sa.UniqueConstraint("edisclosure_id", name=op.f("issuers_edisclosure_id_key")),
        sa.UniqueConstraint("inn", name=op.f("issuers_inn_key")),
        sa.UniqueConstraint("ogrn", name=op.f("issuers_ogrn_key")),
    )
    op.create_index(
        "issuers_name_trgm",
        "issuers",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_table(
        "job_markers",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("job_markers_pkey")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), server_default="user", nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role in ('user','owner')", name=op.f("users_role_check")),
        sa.CheckConstraint("status in ('active','disabled')", name=op.f("users_status_check")),
        sa.CheckConstraint("email = lower(email)", name=op.f("users_email_check")),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("email", name=op.f("users_email_key")),
    )
    op.create_table(
        "web_cache",
        sa.Column("key_hash", sa.LargeBinary(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind in ('search','extract','crawl','map')", name=op.f("web_cache_kind_check")
        ),
        sa.PrimaryKeyConstraint("key_hash", name=op.f("web_cache_pkey")),
    )
    op.create_index("web_cache_expires_idx", "web_cache", ["expires_at"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind in ('register','login','login_failed','logout','logout_all','password_changed','broker_connected','broker_disconnected','broker_verify_failed')",
            name=op.f("audit_events_kind_check"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("audit_events_user_id_fkey"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("audit_events_pkey")),
    )
    op.create_index(
        "audit_events_user_idx",
        "audit_events",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "broker_connections",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("broker", sa.Text(), server_default="tinvest", nullable=False),
        sa.Column("token_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("token_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("token_key_id", sa.Text(), nullable=False),
        sa.Column("token_hint", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("broker in ('tinvest')", name=op.f("broker_connections_broker_check")),
        sa.CheckConstraint(
            "status in ('active','invalid')", name=op.f("broker_connections_status_check")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("broker_connections_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("broker_connections_pkey")),
        sa.UniqueConstraint(
            "user_id", "broker", name=op.f("broker_connections_user_id_broker_key")
        ),
    )
    op.create_table(
        "candles_daily",
        sa.Column("instrument_uid", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=9), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=9), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=9), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=9), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_uid"],
            ["instruments.uid"],
            name=op.f("candles_daily_instrument_uid_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("instrument_uid", "day", name=op.f("candles_daily_pkey")),
    )
    op.create_table(
        "disclosure_documents",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("issuer_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.Text(), server_default="edisclosure", nullable=False),
        sa.Column("source_file_id", sa.BigInteger(), nullable=False),
        sa.Column("section", sa.Text(), nullable=False),
        sa.Column("source_page_url", sa.Text(), nullable=False),
        sa.Column("doc_type_raw", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("standard", sa.Text(), nullable=False),
        sa.Column("period_year", sa.Integer(), nullable=True),
        sa.Column("period_months", sa.Integer(), nullable=True),
        sa.Column("period_label", sa.Text(), nullable=False),
        sa.Column("basis_date", sa.Date(), nullable=True),
        sa.Column("published_date", sa.Date(), nullable=False),
        sa.Column("file_ext", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("fetch_status", sa.Text(), server_default="listed", nullable=False),
        sa.Column("facts_status", sa.Text(), server_default="none", nullable=False),
        sa.Column("index_status", sa.Text(), server_default="none", nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("sha256", sa.LargeBinary(), nullable=True),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("extractor_version", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "facts_status in ('none','done','failed','not_applicable')",
            name=op.f("disclosure_documents_facts_status_check"),
        ),
        sa.CheckConstraint(
            "fetch_status in ('listed','downloaded','failed','skipped')",
            name=op.f("disclosure_documents_fetch_status_check"),
        ),
        sa.CheckConstraint(
            "index_status in ('none','done','failed')",
            name=op.f("disclosure_documents_index_status_check"),
        ),
        sa.CheckConstraint(
            "kind in ('ifrs_annual','ifrs_interim','ras_annual','ras_interim','annual_report','issuer_report','presentation','press_release','other')",
            name=op.f("disclosure_documents_kind_check"),
        ),
        sa.CheckConstraint(
            "section in ('charter','annual','ras','ifrs','issuer_reports','affiliates','emission','investors','other','meetings')",
            name=op.f("disclosure_documents_section_check"),
        ),
        sa.CheckConstraint(
            "source in ('edisclosure')", name=op.f("disclosure_documents_source_check")
        ),
        sa.CheckConstraint(
            "standard in ('ifrs','ras','none')", name=op.f("disclosure_documents_standard_check")
        ),
        sa.CheckConstraint(
            "period_months in (3,6,9,12)", name=op.f("disclosure_documents_period_months_check")
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["issuers.id"],
            name=op.f("disclosure_documents_issuer_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("disclosure_documents_pkey")),
        sa.UniqueConstraint(
            "source", "source_file_id", name=op.f("disclosure_documents_source_source_file_id_key")
        ),
    )
    op.create_index(
        "disclosure_documents_issuer_idx",
        "disclosure_documents",
        ["issuer_id", "kind", sa.literal_column("period_year DESC")],
        unique=False,
    )
    op.create_index(
        "disclosure_documents_pending_idx",
        "disclosure_documents",
        ["fetch_status", "facts_status", "index_status"],
        unique=False,
    )
    op.create_table(
        "invites",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("code_hash", sa.LargeBinary(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_by", sa.Uuid(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("invites_created_by_fkey"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["used_by"], ["users.id"], name=op.f("invites_used_by_fkey"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("invites_pkey")),
        sa.UniqueConstraint("code_hash", name=op.f("invites_code_hash_key")),
        sa.UniqueConstraint("used_by", name=op.f("invites_used_by_key")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("sessions_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sessions_pkey")),
        sa.UniqueConstraint("token_hash", name=op.f("sessions_token_hash_key")),
    )
    op.create_index("sessions_expires_idx", "sessions", ["expires_at"], unique=False)
    op.create_index("sessions_user_idx", "sessions", ["user_id"], unique=False)
    op.create_table(
        "threads",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("title_source", sa.Text(), server_default="auto", nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("summary_upto_id", sa.Uuid(), nullable=True),
        sa.Column("message_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "title_source in ('auto','user')", name=op.f("threads_title_source_check")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("threads_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("threads_pkey")),
    )
    op.create_index(
        "threads_title_trgm",
        "threads",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_index(
        "threads_user_recent_idx",
        "threads",
        ["user_id", sa.literal_column("last_message_at DESC NULLS LAST")],
        unique=False,
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.create_table(
        "usage_daily",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("resource", sa.Text(), nullable=False),
        sa.Column("amount", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("calls", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "resource in ('llm:lite','llm:pro','llm:max','llm:ultra','web:credits')",
            name=op.f("usage_daily_resource_check"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("usage_daily_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.UniqueConstraint(
            "day",
            "user_id",
            "resource",
            name=op.f("usage_daily_day_user_id_resource_key"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index("usage_daily_resource_idx", "usage_daily", ["resource", "day"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("model_mode", sa.Text(), server_default="auto", nullable=False),
        sa.Column("answer_style", sa.Text(), server_default="concise", nullable=False),
        sa.Column("default_account", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "answer_style in ('concise','detailed')", name=op.f("user_settings_answer_style_check")
        ),
        sa.CheckConstraint(
            "model_mode in ('auto','lite','pro','max','ultra')",
            name=op.f("user_settings_model_mode_check"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("user_settings_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("user_settings_pkey")),
    )
    op.create_table(
        "broker_accounts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("opened_at", sa.Date(), nullable=True),
        sa.Column("access_level", sa.Text(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "access_level in ('read_only')", name=op.f("broker_accounts_access_level_check")
        ),
        sa.CheckConstraint("alias ~ '^acc[0-9]+$'", name=op.f("broker_accounts_alias_check")),
        sa.CheckConstraint(
            "status in ('new','open','closed','other')", name=op.f("broker_accounts_status_check")
        ),
        sa.CheckConstraint(
            "type in ('broker','iis','invest_box','invest_fund','other')",
            name=op.f("broker_accounts_type_check"),
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["broker_connections.id"],
            name=op.f("broker_accounts_connection_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("broker_accounts_pkey")),
        sa.UniqueConstraint(
            "connection_id", "alias", name=op.f("broker_accounts_connection_id_alias_key")
        ),
        sa.UniqueConstraint(
            "connection_id",
            "external_id",
            name=op.f("broker_accounts_connection_id_external_id_key"),
        ),
    )
    op.create_table(
        "document_parts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("ext", sa.Text(), nullable=False),
        sa.Column("sha256", sa.LargeBinary(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("pages", sa.Integer(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["disclosure_documents.id"],
            name=op.f("document_parts_document_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("document_parts_pkey")),
        sa.UniqueConstraint(
            "document_id", "name", name=op.f("document_parts_document_id_name_key")
        ),
    )
    op.create_table(
        "financial_facts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("issuer_id", sa.Uuid(), nullable=False),
        sa.Column("standard", sa.Text(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("metric_raw", sa.Text(), nullable=True),
        sa.Column("line_code", sa.Text(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("period_months", sa.Integer(), nullable=False),
        sa.Column("value", sa.Numeric(precision=28, scale=4), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("is_consolidated", sa.Boolean(), nullable=False),
        sa.Column("extraction", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("check_status", sa.Text(), server_default="unchecked", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "check_status in ('ok','mismatch','unchecked')",
            name=op.f("financial_facts_check_status_check"),
        ),
        sa.CheckConstraint(
            "extraction in ('ras_rule','llm','manual')",
            name=op.f("financial_facts_extraction_check"),
        ),
        sa.CheckConstraint(
            "standard in ('ifrs','ras')", name=op.f("financial_facts_standard_check")
        ),
        sa.CheckConstraint(
            "statement in ('income','balance','cashflow')",
            name=op.f("financial_facts_statement_check"),
        ),
        sa.CheckConstraint(
            "period_months in (3,6,9,12)", name=op.f("financial_facts_period_months_check")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["disclosure_documents.id"],
            name=op.f("financial_facts_document_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["issuers.id"],
            name=op.f("financial_facts_issuer_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("financial_facts_pkey")),
        sa.UniqueConstraint(
            "document_id",
            "statement",
            "metric",
            "period_end",
            "period_months",
            name="financial_facts_document_id_statement_metric_period_end_per_key",
        ),
    )
    op.create_index(
        "financial_facts_issuer_idx",
        "financial_facts",
        ["issuer_id", "metric", sa.literal_column("period_end DESC")],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="complete", nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('russian', content)", persisted=True),
            nullable=True,
        ),
        sa.CheckConstraint("role in ('user','assistant')", name=op.f("messages_role_check")),
        sa.CheckConstraint(
            "status in ('complete','partial','failed')", name=op.f("messages_status_check")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name="messages_run_fk",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["threads.id"], name=op.f("messages_thread_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("messages_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("messages_pkey")),
    )
    op.create_index("messages_thread_idx", "messages", ["thread_id", "created_at"], unique=False)
    op.create_index(
        "messages_user_idx",
        "messages",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "messages_user_search_idx", "messages", ["search_tsv"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("user_message_id", sa.Uuid(), nullable=False),
        sa.Column("assistant_message_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column(
            "cancel_requested", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("routing", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_family", sa.Text(), nullable=True),
        sa.Column("model_id", sa.Text(), nullable=True),
        sa.Column("steps", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tokens_billable", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tokens_precached", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("web_credits", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "model_family in ('lite','pro','max','ultra')",
            name=op.f("agent_runs_model_family_check"),
        ),
        sa.CheckConstraint(
            "status in ('queued','running','done','partial','cancelled','failed','interrupted')",
            name=op.f("agent_runs_status_check"),
        ),
        sa.ForeignKeyConstraint(
            ["assistant_message_id"],
            ["messages.id"],
            name=op.f("agent_runs_assistant_message_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
            name=op.f("agent_runs_thread_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("agent_runs_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_message_id"],
            ["messages.id"],
            name=op.f("agent_runs_user_message_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agent_runs_pkey")),
    )
    op.create_index(
        "agent_runs_one_active_idx",
        "agent_runs",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index(
        "agent_runs_thread_idx", "agent_runs", ["thread_id", "created_at"], unique=False
    )
    # use_alter keys are left out of CREATE TABLE: add messages_run_fk once agent_runs exists.
    op.create_foreign_key(
        "messages_run_fk", "messages", "agent_runs", ["run_id"], ["id"], ondelete="SET NULL"
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("total_value", sa.Numeric(precision=24, scale=9), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("expected_yield", sa.Numeric(precision=24, scale=9), nullable=True),
        sa.Column("positions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["broker_accounts.id"],
            name=op.f("portfolio_snapshots_account_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("account_id", "day", name=op.f("portfolio_snapshots_pkey")),
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("local_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind in ('chart','table','image')", name=op.f("artifacts_kind_check")),
        sa.CheckConstraint("local_id ~ '^[cti][0-9]+$'", name=op.f("artifacts_local_id_check")),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("artifacts_message_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("artifacts_run_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("artifacts_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("artifacts_pkey")),
        sa.UniqueConstraint("run_id", "local_id", name=op.f("artifacts_run_id_local_id_key")),
    )
    op.create_index("artifacts_message_idx", "artifacts", ["message_id"], unique=False)
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("job_id", sa.BigInteger(), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("priority", sa.Text(), nullable=False),
        sa.Column("family", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("precached_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("billable_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("wait_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("duration_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "family in ('lite','pro','max','ultra')", name=op.f("llm_calls_family_check")
        ),
        sa.CheckConstraint(
            "priority in ('interactive','background')", name=op.f("llm_calls_priority_check")
        ),
        sa.CheckConstraint(
            "purpose in ('classify','agent_step','synthesize','title','summarize','ifrs_extract','other')",
            name=op.f("llm_calls_purpose_check"),
        ),
        sa.CheckConstraint(
            "status in ('ok','error','timeout','rate_limited','cancelled')",
            name=op.f("llm_calls_status_check"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("llm_calls_run_id_fkey"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("llm_calls_user_id_fkey"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("llm_calls_pkey")),
    )
    op.create_index("llm_calls_created_idx", "llm_calls", ["created_at"], unique=False)
    op.create_index("llm_calls_family_idx", "llm_calls", ["family", "created_at"], unique=False)
    op.create_index("llm_calls_user_idx", "llm_calls", ["user_id", "created_at"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("local_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("publisher", sa.Text(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind in ('web','document','tinvest','edisclosure')", name=op.f("sources_kind_check")
        ),
        sa.CheckConstraint("local_id ~ '^s[0-9]+$'", name=op.f("sources_local_id_check")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["disclosure_documents.id"],
            name=op.f("sources_document_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("sources_message_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("sources_run_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sources_pkey")),
        sa.UniqueConstraint("run_id", "local_id", name=op.f("sources_run_id_local_id_key")),
    )
    op.create_index("sources_message_idx", "sources", ["message_id"], unique=False)
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("tool", sa.Text(), nullable=False),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("result_summary", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("tool_calls_run_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tool_calls_pkey")),
    )
    op.create_index("tool_calls_run_idx", "tool_calls", ["run_id", "step"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint("messages_run_fk", "messages", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("tool_calls_run_idx", table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index("sources_message_idx", table_name="sources")
    op.drop_table("sources")
    op.drop_index("llm_calls_user_idx", table_name="llm_calls")
    op.drop_index("llm_calls_family_idx", table_name="llm_calls")
    op.drop_index("llm_calls_created_idx", table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index("artifacts_message_idx", table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_table("portfolio_snapshots")
    op.drop_index("agent_runs_thread_idx", table_name="agent_runs")
    op.drop_index(
        "agent_runs_one_active_idx",
        table_name="agent_runs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_table("agent_runs")
    op.drop_index("messages_user_search_idx", table_name="messages", postgresql_using="gin")
    op.drop_index("messages_user_idx", table_name="messages")
    op.drop_index("messages_thread_idx", table_name="messages")
    op.drop_table("messages")
    op.drop_index("financial_facts_issuer_idx", table_name="financial_facts")
    op.drop_table("financial_facts")
    op.drop_table("document_parts")
    op.drop_table("broker_accounts")
    op.drop_table("user_settings")
    op.drop_index("usage_daily_resource_idx", table_name="usage_daily")
    op.drop_table("usage_daily")
    op.drop_index(
        "threads_user_recent_idx",
        table_name="threads",
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.drop_index(
        "threads_title_trgm",
        table_name="threads",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_table("threads")
    op.drop_index("sessions_user_idx", table_name="sessions")
    op.drop_index("sessions_expires_idx", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("invites")
    op.drop_index("disclosure_documents_pending_idx", table_name="disclosure_documents")
    op.drop_index("disclosure_documents_issuer_idx", table_name="disclosure_documents")
    op.drop_table("disclosure_documents")
    op.drop_table("candles_daily")
    op.drop_table("broker_connections")
    op.drop_index("audit_events_user_idx", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("web_cache_expires_idx", table_name="web_cache")
    op.drop_table("web_cache")
    op.drop_table("users")
    op.drop_table("job_markers")
    op.drop_index(
        "issuers_name_trgm",
        table_name="issuers",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("issuers")
    op.drop_index(
        "instruments_ticker_trgm",
        table_name="instruments",
        postgresql_using="gin",
        postgresql_ops={"ticker": "gin_trgm_ops"},
    )
    op.drop_index(
        "instruments_name_trgm",
        table_name="instruments",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index("instruments_isin_idx", table_name="instruments")
    op.drop_index("instruments_figi_idx", table_name="instruments")
    op.drop_index("instruments_asset_idx", table_name="instruments")
    op.drop_table("instruments")
    # ### end Alembic commands ###
    op.execute("drop extension if exists pg_trgm")
